### PR TITLE
[TECHNICAL-SUPPORT] LPS-56229 User cannot select calendars for every site which he is a member of

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @brandizzi 

This modification makes a user able to select calendars of sites which he is a member of, in the "Add Event" window.

Could you please review it?

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lipusz** [comment]
Hi Guys,

It seems like the SessionClicks updates are used in a mixed-way: sometimes you specify the a nameSpace "calendar-portlet" while in other cases you don't.

For example, "otherCalendars" is stored without a namespace (see: view_calendar.jsp#L250), while the "visible" and "color" params are stored with "calendar-portlet-calendar*" prefix (see: view_calendar.jsp#L307).

I suggested István to incorporate https://github.com/lipusz/liferay-plugins-ee/commit/4241f17ab8301f48d2f90c4062fea874c6a80117 in this pull, but I'd like to know if the current logic is fine or not.

Thx!

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/istvanD/liferay-plugins/pull/10. [See changes here.](https://github.com/brandizzi/liferay-plugins/compare/aff0d56~1...aff0d56) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
@lipusz

Hello Tibor!

I don't see where the "Other Calendars" session click is stored without prefix: both in master (https://github.com/liferay/liferay-plugins/blob/a4381b7ef/portlets/calendar-portlet/docroot/view_calendar.jsp#L250-L252) and ee-6.2.x (https://github.com/liferay/liferay-plugins-ee/blob/4d720818/portlets/calendar-portlet/docroot/view_calendar.jsp#L250-L252) it is stored as `calendar-portlet-other-calendars`. The prefix here is `calendar-portlet-` and can be seen at line 252.

What we see at like 311 (https://github.com/liferay/liferay-plugins/blob/a4381b7ef/portlets/calendar-portlet/docroot/view_calendar.jsp#L307-L311) use the very same prefix `calendar-portlet-`. The calendar that follows it is to make clear this session click store information about a specific calendar. So, if we are going to set the visibility to the calendar whose id is 20321, this session click would be `calendar-portlet-calendar-20321-visible`. The prefix is `calendar-portlet-` and the "actual" session click name is `calendar-20321-visible`. `otherCalendars` are variable names, not keys to the session clicks.

Given that, the change from https://github.com/lipusz/liferay-plugins-ee/commit/4241f17ab8301f48d2f90c4062fea874c6a80117 is not needed. In fact, it will probably break the calendar, since then it will try to get a session click with a name but the used name is the other. The pull request is perfect except for this change.

Anyway, I'm submitting this pull request back to @IstvanD without the session click change (https://github.com/istvanD/liferay-plugins/pull/10) because it will not be merged into master. We were forced to make a huge change on the calendar and it will be inside liferay-portal now. Once it is merged, the calendar will be removed from the plugins and due to that everybody else is refusing merged into the plugins' master. (More about it here: https://in.liferay.com/web/global.engineering/forums/-/message_boards/message/15587300)

Since I cannot merge it into master, I'd recommend you to release a fix to the customer and later we will figure out what to do with the master.

I'm sorry for this inconvenience :-/

**Comment by lipusz** [comment]
OK, now I see it.
Someone made a regression on the temporary release branch:
https://github.com/lipusz/liferay-plugins-ee/blob/social-office-ee-3.0.2-EVAKIRVOW-6210/portlets/calendar-portlet/docroot/view_calendar.jsp#L250
That's why I made that SF.

Of course, I agree with you that this is not needed for master/ee-6.2.x

Thank you for looking into this. ;-)

The universe is safe, again. :-]

Cheers,
Tibor

On Fri, Jun 19, 2015 at 6:31 PM, Adam Victor Nazareth Brandizzi <
notifications@github.com> wrote:

> @lipusz <https://github.com/lipusz>
>
> Hello Tibor!
>
> I don't see where the "Other Calendars" session click is stored without
> prefix: both in master (
> https://github.com/liferay/liferay-plugins/blob/a4381b7ef/portlets/calendar-portlet/docroot/view_calendar.jsp#L250-L252)
> and ee-6.2.x (
> https://github.com/liferay/liferay-plugins-ee/blob/4d720818/portlets/calendar-portlet/docroot/view_calendar.jsp#L250-L252)
> it is stored as calendar-portlet-other-calendars. The prefix here is
> calendar-portlet- and can be seen at line 252.
>
> What we see at like 311 (
> https://github.com/liferay/liferay-plugins/blob/a4381b7ef/portlets/calendar-portlet/docroot/view_calendar.jsp#L307-L311)
> use the very same prefix calendar-portlet-. The calendar that follows it
> is to make clear this session click store information about a specific
> calendar. So, if we are going to set the visibility to the calendar whose
> id is 20321, this session click would be
> calendar-portlet-calendar-20321-visible. The prefix is calendar-portlet-
> and the "actual" session click name is calendar-20321-visible.
> otherCalendars are variable names, not keys to the session clicks.
>
> Given that, the change from lipusz/liferay-plugins-ee@4241f17
> <https://github.com/lipusz/liferay-plugins-ee/commit/4241f17ab8301f48d2f90c4062fea874c6a80117>
> is not needed. In fact, it will probably break the calendar, since then it
> will try to get a session click with a name but the used name is the other.
> The pull request is perfect except for this change.
>
> Anyway, I'm submitting this pull request back to @IstvanD
> <https://github.com/IstvanD> without the session click change (IstvanD#10
> <https://github.com/IstvanD/liferay-plugins/pull/10>) because it will not
> be merged into master. We were forced to make a huge change on the calendar
> and it will be inside liferay-portal now. Once it is merged, the calendar
> will be removed from the plugins and due to that everybody else is refusing
> merged into the plugins' master. (More about it here:
> https://in.liferay.com/web/global.engineering/forums/-/message_boards/message/15587300
> )
>
> Since I cannot merge it into master, I'd recommend you to release a fix to
> the customer and later we will figure out what to do with the master.
>
> I'm sorry for this inconvenience :-/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brandizzi/liferay-plugins/pull/91#issuecomment-113567144>
> .
>



-- 

*Tibor LIPUSZ*

Senior Software Engineer @ TS
Security SME, Subscription Services & Release, Global


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

 *Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

 <http://www.liferay.com>

**Comment by brandizzi** [comment]
@lipusz oh, ok, now that makes sense :laughing: 

I believe my PR will fix the regression. Please let me know of any problems. I can't ensure the world is safe but the calendar is a bit less in danger now :stuck_out_tongue_winking_eye:

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/inacionery/liferay-plugins/pull/1. [See changes here.](https://github.com/brandizzi/liferay-plugins/compare/aff0d56~1...aff0d56) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
