### PR TITLE
LPS-53072

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
depends on https://github.com/brandizzi/liferay-plugins/pull/71

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
See https://issues.liferay.com/browse/LPS-53072?focusedCommentId=575120&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-575120 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by BryanEngler** [comment]
new pr at https://github.com/brandizzi/liferay-plugins/pull/72

**Pull request closed without merging**
