### PR TITLE
LPS-53057

### PR DESCRIPTION
**Pull request by bejondshao**

### CODE REVIEW

**Comment by bejondshao** [comment]
Hi Adam,

I realize that my change doesn't belongs to LPS-53057 actually. So would you confirm my fix and then, if it's ok commit in the same LPS?

Thanks

**Comment by brandizzi** [comment]
Hello Bejond!

Your change has a problem: with this property set, ALL USERS will be able to create approved events in the site. If a user creates an event in a personal calendar and invites the site calendar to event, the event in the site calendar will be approved by default - and the user not even needs to be a site member.

This change seems even unnecessary, because if you want all events created by a user in a site calendar to be auto-approved, then the user already has the MANAGE_BOOKINGS permission. The only situation where a user without this permission can create an event in a site calendar is by inviting the site calendar - and I don't really think you want these events to be auto-approved.

For this, I'd rather not merge your change.

If I'm missing something, please let me know.

**Comment by bejondshao** [comment]
Hi Adam,

Your reason is right, but it depends customer's requirements. 

Customer uses calendar 6.1 and upgrade to 6.2. In 6.1, there's no status of an event, he can directly view events in related assets. It also means any user can add events to site calendar, and then the events are available. 
But in 6.2, we tell him that the events have to be approved first to show in related assets, which is inconsistent with 6.1.

So your fix only gives auto-approved permission to event manager. But it still can't solve customer's problem. Not all users can have "manage event" permission.

I think we should make a alternative property to make customer use old workflow. That also means, if customer uses this property, he knows what will happen first. 

So my property means, a user can create a site event and make it available right now. But he can't edit event in site because he doesn't have "manage event" permission.

PS: would you notice another LPS? LPS-52467

Thank you
Bejond

**Comment by brandizzi** [comment]
Answered in [Social Office](https://in.liferay.com/web/global.engineering/forums/-/message_boards/message/5486603)

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Closed. We got a compromise with a different approach.

See https://github.com/marcellustavares/liferay-plugins/pull/261 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
