### PR TITLE
LPS-55080 Calendar portlet, weekdays in the mini calendar are not affected by calendar's 'Week Starts On' configuration

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @brandizzi 

Could you please review this pull?

The branch of the portal side counterpart is:
https://github.com/IstvanD/liferay-portal-ee/commits/fix-pack-LPP-16177

However, it will be provided as SDH, so it is based on ee-6.2.10-sp10.

Thank you.

Best regards,
István

### CODE REVIEW

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Hello @IstvanD!

Is there a ticket for the change in the portal? I'd rather merge both at once. Can we do that?

**Comment by IstvanD** [comment]
Hey @brandizzi 

The ticket for the portal sided solution is the same as that of the plugin side: LPS-55080

The reason why they are handled separately is that for portal changes, we are processing them as Support Driven Hotfixes (SDH), which means, we fist implement them on the customers portal version.
In our case this is 6.2.10-sp10.

The rationale of this is that it is not necessary to file the changes to master, and wait until it is backported to the customers branch. We can do this parallel, but the customer can get his solution more timely.

However, for plugin issues, we don't follow this process. We still sent the changes to the master branch, and wait until gets backported.

So when there is an issue which's solution has both a portal and a plugin part, this gets a little bit difficult. We create the hotfix for the portal, but still have to wait for the backport of the plugin solution.

If you wish, I can send you a pull request with the changes on the portal, but on the master.

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-plugins/pull/98. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
