### PR TITLE
LPS-56626

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @dustinryerson

### CODE REVIEW

**Comment by dustinryerson** [comment]
Hey @brandizzi,

Will you have time to review this pull soon? If not, that's totally ok, but should we send to someone else? It's for a customer so I am just trying to ensure I work on their behalf. Please let me know.

Thank you in advance!

**Comment by dustinryerson** [comment]
@brandizzi any update on this one?

**Comment by dustinryerson** [comment]
After seeing your Vacation response from email, resent to Marcellus: https://github.com/marcellustavares/liferay-plugins/pull/297

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-plugins/pull/105. [See changes here.](https://github.com/brandizzi/liferay-plugins/compare/63f2534~1...63f2534) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
